#Powers server settings
#Sun Jun 21 15:31:14 CDT 2026
chunkUpdateIntervalTicks=40
craftedHeartValue=1
duplicateHeartCost=2
forceLoadChunkRadius=1
keepDuplicatesLoadedWhileOffline=true
maxForceLoadedDuplicates=128
maxPlayerHearts=20
minimumHeartsAfterDuplicate=1
nearbyPlayerRadius=80
playerKillHeartReward=1
